#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;
use Minicli\Command\CommandCall;
 
	$app = new App();
	$app->setSignature('./mercadolibre items');
	$app->registerCommand('items', function(CommandCall $input) {

	$seller_id = $input->getParam('seller_id');


	$client = new GuzzleHttp\Client();
	
	
	
	$url_seller = "https://api.mercadolibre.com/sites/MLA/search?seller_id=$seller_id";
	
		
	$res = $client->request('GET', $url_seller);

	$body = $res->getBody();
	
	$response = json_decode($body);

	$products = $response->results;

	$categories = [];


	foreach ($products as $key => $product) {
	

		if(!array_key_exists($product->category_id, $categories))
		{
			$res = $client->request('GET',"https://api.mercadolibre.com/categories/$product->category_id");
		
			$body = $res->getBody();
		
			$category = json_decode($body);

			$categories[$category->id] = $category->name;			
		}

		$category_name = $categories [$product->category_id];
	
		echo "{$product->id}, {$product->title}, {$product->category_id}, {$category_name}\n";
	}

});

$app->runCommand($argv);